=== kaelhawaty/JDBC-DBMS/ddd/test.dtd
<!ELEMENT Table (ID,name,age,birth,gpa)>
<!ATTLIST Table
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED>

<!ELEMENT ID (Record,Record,Record,Record,Record)>
<!ATTLIST ID
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT name (Record,Record,Record,Record,Record)>
<!ATTLIST name
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT age (Record,Record,Record,Record,Record)>
<!ATTLIST age
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT birth (Record,Record,Record,Record,Record)>
<!ATTLIST birth
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT gpa (Record,Record,Record,Record,Record)>
<!ATTLIST gpa
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT Record (#PCDATA)>
<!ATTLIST Record
  xmlns CDATA #FIXED ''>

=== kaelhawaty/JDBC-DBMS/ddd/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Table SYSTEM "test.dtd">
<Table name="test">
    <ID type="int">
        <Record>0</Record>
        <Record>1</Record>
        <Record>2</Record>
        <Record>3</Record>
        <Record>4</Record>
    </ID>
    <name type="varchar">
        <Record>'Hazem'</Record>
        <Record>'Karmola'</Record>
        <Record>'M7osy'</Record>
        <Record>'Beke'</Record>
        <Record>'Hazem'</Record>
    </name>
    <age type="int">
        <Record>20</Record>
        <Record>3</Record>
        <Record>1000</Record>
        <Record>1</Record>
        <Record>20</Record>
    </age>
    <birth type="date">
        <Record>29/05/1999</Record>
        <Record>01/01/2000</Record>
        <Record>01/01/1980</Record>
        <Record>01/01/2010</Record>
        <Record>29/05/1999</Record>
    </birth>
    <gpa type="float">
        <Record>0.565</Record>
        <Record>9.0</Record>
        <Record>4.0</Record>
        <Record>3.95</Record>
        <Record>0.565</Record>
    </gpa>
</Table>
