=== kaelhawaty/JDBC-DBMS/sample/59602/testdb_update/table_name8.dtd
<!ELEMENT Table (ID,column_name1,column_name2,column_name3)>
<!ATTLIST Table
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED>

<!ELEMENT ID (Record,Record,Record)>
<!ATTLIST ID
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT column_name1 (Record,Record,Record)>
<!ATTLIST column_name1
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT column_name2 (Record,Record,Record)>
<!ATTLIST column_name2
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT column_name3 (Record,Record,Record)>
<!ATTLIST column_name3
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT Record (#PCDATA)>
<!ATTLIST Record
  xmlns CDATA #FIXED ''>

=== kaelhawaty/JDBC-DBMS/DatabasesWorkSpace/sample/32650/testdb_update/table_name8.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Table SYSTEM "table_name8.dtd">
<Table name="table_name8">
    <ID type="int">
        <Record>0</Record>
        <Record>1</Record>
        <Record>2</Record>
    </ID>
    <column_name1 type="varchar">
        <Record>'11111111'</Record>
        <Record>'11111111'</Record>
        <Record>'value2'</Record>
    </column_name1>
    <column_name2 type="int">
        <Record>22222222</Record>
        <Record>22222222</Record>
        <Record>5</Record>
    </column_name2>
    <column_name3 type="varchar">
        <Record>'333333333'</Record>
        <Record>'333333333'</Record>
        <Record>'value4'</Record>
    </column_name3>
</Table>
