=== kaelhawaty/JDBC-DBMS/testdb/hazoma.dtd
<!ELEMENT Table (ID,name,age)>
<!ATTLIST Table
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED>

<!ELEMENT ID (Record,Record)>
<!ATTLIST ID
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT name (Record,Record)>
<!ATTLIST name
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT age (Record,Record)>
<!ATTLIST age
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT Record (#PCDATA)>
<!ATTLIST Record
  xmlns CDATA #FIXED ''>

=== kaelhawaty/JDBC-DBMS/testdb/hazoma.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Table SYSTEM "hazoma.dtd">
<Table name="hazoma">
    <ID type="int">
        <Record>0</Record>
        <Record>1</Record>
    </ID>
    <name type="varchar">
        <Record>'kareem'</Record>
        <Record>'hazoma'</Record>
    </name>
    <age type="int">
        <Record>25</Record>
        <Record>15</Record>
    </age>
</Table>
